version: '3.4'

services:
  mongo:
    image: mongo:4.4.10
    ports:
      - "27017:27017"
    volumes:
      - ~/data/mongo:/data/db

  api:
    image: api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ~/data/storage:/app/storage